site_name: Regelum
site_description: Modular framework for pipeline construction
site_author: AIDA Group

# Repository
repo_name: aidagroup/regelum
repo_url: https://github.com/aidagroup/regelum

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Navigation
nav:
  - Home: index.md
  - Learn: learn.md


# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

# Extra settings
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/username